# Generated by Django 4.2 on 2025-06-09 00:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('comments', models.TextField()),
                ('sentiment_results', models.TextField()),
                ('word_frequency', models.TextField()),
                ('csv_file', models.FileField(upload_to='csv/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pie_chart', models.ImageField(blank=True, null=True, upload_to='charts/pie/')),
                ('bar_chart', models.ImageField(blank=True, null=True, upload_to='charts/bar/')),
                ('analysis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='youtubeApi.dokument')),
            ],
        ),
    ]
